//! # l_46_push_crate_autogenerated_docs
//!
//! `l_46_push_crate_autogenerated_docs` is a collection of utilities to make performing certain
//! calculations more convenient.

/// Adds one to the number given.
// --snip--

///Adds one to the number given.
///
/// # Arguments
///
/// * `x`:
///
/// returns: i32
///
/// # Examples
///
/// ```
/// let five = 5;///
/// let answer = l_46_push_crate_autogenerated_docs::add_one(five);
///
/// assert_eq!(6, answer);
/// ```
pub fn add_one(x: i32) -> i32 {
    x + 1
}